# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui_files/parameters_change.ui'
#
# Created: Thu Jul 10 19:03:54 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName("formLayout_3")
        self.Top_Velocity_2 = QtGui.QLabel(Dialog)
        self.Top_Velocity_2.setObjectName("Top_Velocity_2")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.Top_Velocity_2)
        self.Top_Velocity_Edit_2 = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Top_Velocity_Edit_2.sizePolicy().hasHeightForWidth())
        self.Top_Velocity_Edit_2.setSizePolicy(sizePolicy)
        self.Top_Velocity_Edit_2.setFrame(True)
        self.Top_Velocity_Edit_2.setReadOnly(False)
        self.Top_Velocity_Edit_2.setObjectName("Top_Velocity_Edit_2")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.Top_Velocity_Edit_2)
        self.Cutoff_Velocity_2 = QtGui.QLabel(Dialog)
        self.Cutoff_Velocity_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Cutoff_Velocity_2.setObjectName("Cutoff_Velocity_2")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.Cutoff_Velocity_2)
        self.Cutoff_Velocity_Edit_2 = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cutoff_Velocity_Edit_2.sizePolicy().hasHeightForWidth())
        self.Cutoff_Velocity_Edit_2.setSizePolicy(sizePolicy)
        self.Cutoff_Velocity_Edit_2.setFrame(True)
        self.Cutoff_Velocity_Edit_2.setReadOnly(False)
        self.Cutoff_Velocity_Edit_2.setObjectName("Cutoff_Velocity_Edit_2")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.Cutoff_Velocity_Edit_2)
        self.Start_Velocity_2 = QtGui.QLabel(Dialog)
        self.Start_Velocity_2.setObjectName("Start_Velocity_2")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.Start_Velocity_2)
        self.Start_Velocity_Edit_2 = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Start_Velocity_Edit_2.sizePolicy().hasHeightForWidth())
        self.Start_Velocity_Edit_2.setSizePolicy(sizePolicy)
        self.Start_Velocity_Edit_2.setFrame(True)
        self.Start_Velocity_Edit_2.setReadOnly(False)
        self.Start_Velocity_Edit_2.setObjectName("Start_Velocity_Edit_2")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.Start_Velocity_Edit_2)
        self.Backlash_Steps_2 = QtGui.QLabel(Dialog)
        self.Backlash_Steps_2.setObjectName("Backlash_Steps_2")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.Backlash_Steps_2)
        self.Backlash_Steps_Edit_2 = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Backlash_Steps_Edit_2.sizePolicy().hasHeightForWidth())
        self.Backlash_Steps_Edit_2.setSizePolicy(sizePolicy)
        self.Backlash_Steps_Edit_2.setFrame(True)
        self.Backlash_Steps_Edit_2.setReadOnly(False)
        self.Backlash_Steps_Edit_2.setObjectName("Backlash_Steps_Edit_2")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.Backlash_Steps_Edit_2)
        self.SlopeEdit = QtGui.QLineEdit(Dialog)
        self.SlopeEdit.setText("")
        self.SlopeEdit.setObjectName("SlopeEdit")
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.SlopeEdit)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.Top_Velocity_2.setText(QtGui.QApplication.translate("Dialog", "Top Velocity [kHz/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.Cutoff_Velocity_2.setText(QtGui.QApplication.translate("Dialog", "Cutoff Velocity [kHz/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.Start_Velocity_2.setText(QtGui.QApplication.translate("Dialog", "Start Velocity [kHz/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.Backlash_Steps_2.setText(QtGui.QApplication.translate("Dialog", "Backlash Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Slope", None, QtGui.QApplication.UnicodeUTF8))

